-- DROP SCHEMA IF EXISTS ecommerce;
CREATE SCHEMA ecommerce;

USE ecommerce;

-- DROP TABLE IF EXISTS products; 
CREATE TABLE products(PID INT AUTO_INCREMENT,
DESCRIPTION TEXT NOT NULL,
PRODUCT_NAME VARCHAR(255) NOT NULL,
PRICE DOUBLE NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY(PID)
);

-- DROP TABLE IF EXISTS users;
CREATE TABLE users(
ID INT AUTO_INCREMENT,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
USERNAME VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
ROLE ENUM("admin","user","guest") NOT NULL,
ISlOGGEDIN BOOLEAN,
ISACTIVE BOOLEAN,
PRIMARY KEY(ID)
);

